site:
  # each line is a partition (Raft group), first 3 sites are replicas (no learner in Raft)
  # Use ports 55xxx to avoid conflicts with common services
  server:
    - ["s101:55001", "s201:55101", "s301:55201"]
    - ["s102:55002", "s202:55102", "s302:55202"]

# s101: localhost
# s201: p1
# s301: p2
process:
  s101: localhost
  s201: p1
  s301: p2
  s102: localhost
  s202: p1
  s302: p2

# process_name - host_addr map
host:
  localhost: 127.0.0.1
  p1: 127.0.0.1
  p2: 127.0.0.1
